// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhbo4sAPFku8Qg9-t4J3Add0eJRSdjxw',
    appId: '1:277312780097:web:2d81bc18d6d423058b93c0',
    messagingSenderId: '277312780097',
    projectId: 'fir-notifications-dac5a',
    authDomain: 'fir-notifications-dac5a.firebaseapp.com',
    storageBucket: 'fir-notifications-dac5a.appspot.com',
    measurementId: 'G-M771WNT968',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA62E7lI8vUNpv6SJih5gUW8qiM8kclcNc',
    appId: '1:277312780097:android:a963d58cb8a7ce558b93c0',
    messagingSenderId: '277312780097',
    projectId: 'fir-notifications-dac5a',
    storageBucket: 'fir-notifications-dac5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8ytcvlULTbbej6ViBcXuRTzxEjtNjCE',
    appId: '1:277312780097:ios:3310a28cd19d25758b93c0',
    messagingSenderId: '277312780097',
    projectId: 'fir-notifications-dac5a',
    storageBucket: 'fir-notifications-dac5a.appspot.com',
    iosClientId: '277312780097-qrsj5p11s97mv95it2jb2plthch5gaso.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotificationTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8ytcvlULTbbej6ViBcXuRTzxEjtNjCE',
    appId: '1:277312780097:ios:3c298dd96cca7ac48b93c0',
    messagingSenderId: '277312780097',
    projectId: 'fir-notifications-dac5a',
    storageBucket: 'fir-notifications-dac5a.appspot.com',
    iosClientId: '277312780097-g644hlm54c87cjkfn3pckg191lf75bl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotificationTesting.RunnerTests',
  );
}
